export interface HazardIssue {
  id: string;
  trackingId: string;
  title: string;
  type: "Pothole" | "Broken Streetlight" | "Waterlogging" | "Open Manhole" | "Harassment Spot" | "Road Debris";
  severity: 1 | 2 | 3 | 4 | 5;
  exposureCount: number; // Daily commuters/pedestrians affected
  priorityScore: number; // Exposure-weighted score (Severity * Exposure / 100)
  location: {
    lat: number;
    lng: number;
    address: string;
    ward: string;
  };
  reportedAt: string;
  slaMinutesRemaining: number;
  slaFormatted: string;
  status: "Pending" | "In Progress" | "Resolved";
  beforePhoto: string;
  afterPhoto?: string;
  aiClassification: {
    detectedObject: string;
    confidence: number;
    hazardIndex: string;
    impactDescription: string;
  };
  clarifications?: {
    question: string;
    answer?: string;
  }[];
  resolutionNotes?: string;
  confirmationsCount?: number;
  isClustered?: boolean;
  isSample?: boolean;
}

export interface RouteOption {
  id: "fastest" | "safest";
  name: string;
  duration: string;
  durationMinutes: number;
  distance: string;
  distanceKm: number;
  safetyScore: number; // 0-100
  color: string;
  description: string;
  highlights: string[];
  hazardsAvoided: number;
  lightingQuality: "Poor" | "Moderate" | "Well Lit";
  coordinates: [number, number][];
}

// Center reference: Hyderabad GHMC (Central Corridor: 17.385, 78.4867)
export const MOCK_BASE_COORDINATES: [number, number] = [17.385, 78.4867];

export const MOCK_ISSUES: HazardIssue[] = [
  {
    id: "iss-101",
    trackingId: "SAMPLE-GHMC-01",
    title: "Deep Pothole at Cyber Towers Incline",
    type: "Pothole",
    severity: 5,
    exposureCount: 4200,
    priorityScore: 210,
    location: {
      lat: 17.4504,
      lng: 78.3808,
      address: "Hitec City Main Rd, Cyber Towers Junction",
      ward: "Circle 20 - Serilingampally (Madhapur & Hitec City)",
    },
    reportedAt: "35 mins ago",
    slaMinutesRemaining: 85,
    slaFormatted: "1h 25m left",
    status: "Pending",
    beforePhoto: "https://images.unsplash.com/photo-1515162816999-a0c47dc192f7?w=600&auto=format&fit=crop&q=80",
    aiClassification: {
      detectedObject: "Deep Asphalt Cavity",
      confidence: 96,
      hazardIndex: "Severe Roadway Hazard",
      impactDescription: "High risk of 2-wheeler skidding and wheel rim fracture during evening rush hour.",
    },
    isSample: true,
  },
  {
    id: "iss-102",
    trackingId: "SAMPLE-GHMC-02",
    title: "Faulty Luminaire Array on Cable Bridge Approach",
    type: "Broken Streetlight",
    severity: 4,
    exposureCount: 3850,
    priorityScore: 154,
    location: {
      lat: 17.4259,
      lng: 78.4215,
      address: "Road No. 36 Approach to Durgam Cheruvu",
      ward: "Circle 18 - Jubilee Hills & Banjara Hills",
    },
    reportedAt: "2 hours ago",
    slaMinutesRemaining: 180,
    slaFormatted: "3h 00m left",
    status: "In Progress",
    beforePhoto: "https://images.unsplash.com/photo-1509114397022-ed747cca3f65?w=600&auto=format&fit=crop&q=80",
    aiClassification: {
      detectedObject: "Extinguished Luminaire Pole Array",
      confidence: 92,
      hazardIndex: "High Vulnerability Dark Zone",
      impactDescription: "Low illumination across pedestrian corridor after dusk.",
    },
    isSample: true,
  },
  {
    id: "iss-103",
    trackingId: "SAMPLE-GHMC-03",
    title: "Damaged Drainage Grate near Charminar Market",
    type: "Open Manhole",
    severity: 5,
    exposureCount: 3100,
    priorityScore: 155,
    location: {
      lat: 17.3616,
      lng: 78.4747,
      address: "Pathergatti Road, Near Charminar South Gate",
      ward: "Circle 10 - Charminar & Old City",
    },
    reportedAt: "3 hours ago",
    slaMinutesRemaining: 45,
    slaFormatted: "45m left",
    status: "Pending",
    beforePhoto: "https://images.unsplash.com/photo-1584467735871-8e85353a8413?w=600&auto=format&fit=crop&q=80",
    aiClassification: {
      detectedObject: "Displaced Cast Iron Drainage Grate",
      confidence: 98,
      hazardIndex: "Critical Life Safety Hazard",
      impactDescription: "Exposed opening on pedestrian carriageway.",
    },
    isSample: true,
  },
  {
    id: "iss-104",
    trackingId: "SAMPLE-GHMC-04",
    title: "Few & Broken Streetlights on Villa Access Road",
    type: "Broken Streetlight",
    severity: 4,
    exposureCount: 2800,
    priorityScore: 112,
    location: {
      lat: 17.3245,
      lng: 78.6172,
      address: "Sy No. 246, 248 & 249, Pedda Amberpet Municipality",
      ward: "Pedda Amberpet Municipality (New Life Villas & ORR Exit 11)",
    },
    reportedAt: "45 mins ago",
    slaMinutesRemaining: 120,
    slaFormatted: "2h 00m left",
    status: "Pending",
    beforePhoto: "https://images.unsplash.com/photo-1509114397022-ed747cca3f65?w=600&auto=format&fit=crop&q=80",
    aiClassification: {
      detectedObject: "Sparse / Extinguished Streetlights",
      confidence: 94,
      hazardIndex: "Low Illumination Hazard",
      impactDescription: "Only few functional streetlights on interior access lane to New Life Villas. Recommended to follow illuminated NH65 / ORR corridor.",
    },
    isSample: true,
  },
];

export const MOCK_DESTINATIONS: {
  name: string;
  address: string;
  distance: string;
  coordinates: [number, number];
}[] = [
  {
    name: "New Life Villas, Pedda Amberpet",
    address: "Sy No. 246 , 248 & 249 Pedda Amberpet Municipality, Hyderabad, Telangana 501513",
    distance: "14.2 km",
    coordinates: [17.3231, 78.6185],
  },
  {
    name: "Charminar & Old City",
    address: "Pathergatti, Hyderabad",
    distance: "2.8 km",
    coordinates: [17.3616, 78.4747],
  },
  {
    name: "Secunderabad Railway Station",
    address: "Station Road, Secunderabad",
    distance: "5.6 km",
    coordinates: [17.4344, 78.5017],
  },
  {
    name: "Cyber Towers, Hitec City",
    address: "Hitec City Main Road, Madhapur",
    distance: "9.2 km",
    coordinates: [17.4504, 78.3808],
  },
  {
    name: "Banjara Hills Road No. 1",
    address: "Banjara Hills, Hyderabad",
    distance: "4.1 km",
    coordinates: [17.4156, 78.4354],
  },
  {
    name: "Gachibowli Stadium",
    address: "Old Mumbai Highway, Gachibowli",
    distance: "11.5 km",
    coordinates: [17.4474, 78.3489],
  },
  {
    name: "Kukatpally KPHB Colony",
    address: "KPHB Main Road, Kukatpally",
    distance: "13.0 km",
    coordinates: [17.4933, 78.3995],
  },
];

export const MOCK_ROUTES: RouteOption[] = [
  {
    id: "fastest",
    name: "Direct Route (Shortcut)",
    duration: "14 mins",
    durationMinutes: 14,
    distance: "3.2 km",
    distanceKm: 3.2,
    safetyScore: 58,
    color: "rgba(62, 0, 12, 0.45)",
    description: "Shortest route through interior lanes, with reported unlit street segments.",
    highlights: ["14 mins (Fastest)", "3.2 km", "Safety: 58/100", "Passes unlit lane near interior stretch"],
    hazardsAvoided: 0,
    lightingQuality: "Poor",
    coordinates: [
      [17.385, 78.4867],
      [17.395, 78.49],
      [17.41, 78.495],
      [17.425, 78.499],
      [17.4344, 78.5017],
    ],
  },
  {
    id: "safest",
    name: "Safe Illuminated Corridor",
    duration: "18 mins",
    durationMinutes: 18,
    distance: "3.9 km",
    distanceKm: 3.9,
    safetyScore: 94,
    color: "#3E000C",
    description: "Follows continuous streetlighting along major arterial roads, avoiding reported hazards.",
    highlights: ["18 mins", "3.9 km", "Safety: 94/100 (Safe Corridor)", "Well-lit arterial streetlighting"],
    hazardsAvoided: 3,
    lightingQuality: "Well Lit",
    coordinates: [
      [17.385, 78.4867],
      [17.392, 78.482],
      [17.408, 78.485],
      [17.422, 78.492],
      [17.4344, 78.5017],
    ],
  },
];

export const TRANSLATIONS: Record<string, Record<string, string>> = {
  EN: {
    appName: "Raastha",
    tagline: "Voice-First Civic Safety Platform",
    reportProblem: "Report a Hazard",
    reportProblemSub: "Snap photo or speak to report road hazards instantly",
    safeRoute: "Safe Route",
    safeRouteSub: "Illuminated corridor navigation avoiding road defects",
    myReports: "My Reports",
    myReportsSub: "Track live status and verified contractor proofs",
    voicePromptPlaceholder: "Tap mic or say 'Report pothole' or 'Find safe route'",
    listening: "Listening for voice command...",
    speakNow: "Speak now in your language...",
    authorityPortal: "Official Ward Command",
    sosButton: "Emergency SOS",
    sosTriggered: "Emergency Location Sharing",
    sosDesc: "Share your live location instantly through WhatsApp, SMS, or 112 direct call.",
    fastestRoute: "Direct Route",
    safestRoute: "Safe Illuminated Corridor",
    startNavigation: "Start Safe Navigation",
    priorityScore: "Priority Score",
    exposureCount: "Exposure Volume",
    slaTimer: "SLA Deadline",
    verifyFix: "Verify Fix",
    reportSuccess: "Report submitted successfully. Your tracking ID is",
    navStart: "Starting safe corridor navigation to",
    navArrived: "You have arrived at your destination safely via the illuminated corridor!",
    sosActivated: "Emergency alert triggered. Please share your location or dial 112.",
    wardLabel: "Circle 8 - Abids & Nampally (Central Zone), Hyderabad",
    exposureRanked: "Ranked by exposure = (severity × daily commuters) / 100",
    offlineNotice: "You are currently offline. Changes will sync once reconnected.",
    dispatchSquad: "Dispatch Municipal Squad",
    assigningSquad: "Assigning Squad...",
    verifyResolve: "Verify & Resolve Fix with AI",
    fixNeutralized: "Fix Approved & Neutralized",
    gpsDenied: "GPS access denied or unavailable. Using central corridor coordinates.",
    micDenied: "Microphone access denied. Please use text input below.",
    voiceOpeningReport: "Opening hazard report form...",
    voiceOpeningRoute: "Finding safe illuminated corridor...",
    voiceOpeningMyReports: "Opening your reported issues...",
    voiceOpeningSOS: "Opening emergency assistance sheet...",
    voiceUnknownCommand: "Command not recognized. Try 'Report', 'Safe Route', 'My Reports', or 'SOS'.",
    sosAppsNotice: "These buttons open your own phone apps. Raastha does not send alerts on its own.",
    sampleDataBadge: "Sample Data",
    liveReportBadge: "Live Report",
    adminPortalTitle: "Exposure-Weighted Municipal Dispatch",
    adminPortalSubtitle: "Auto-ranked municipal queue: Priority = (Severity × Commuter Volume Proxy) / 100 with 30m duplicate clustering",
    adminQueueTitle: "Prioritized Incident Dispatch Queue",
    statTotalIssues: "Total Active Issues",
    statSlaOverdue: "SLA Overdue",
    statUnitsDispatched: "Active Units Dispatched",
    statCommutersProtected: "Commuters Protected",
    filterAllCircles: "All Hyderabad Circles",
    filterAllTypes: "All Hazard Types",
    signOut: "Sign Out",
    navSelectDestination: "Select Destination",
    navIlluminatedCorridor: "Illuminated Safe Corridor Navigation",
    navSubtitle: "GPS-guided route optimization prioritizing well-lit arterial streets",
    turnByTurnNav: "Turn-by-Turn Navigation",
    nextDirection: "Next Step",
    destinationReached: "Destination Reached",
    voiceCommandBtn: "Voice Command",
    wardSelectLabel: "Municipal Circle / Ward",
    wardAutoDetected: "Auto-detected from coordinates (editable)",
    liveNavActive: "Live Navigation Active",
    endTrip: "End Trip",
    voiceGuidance: "Voice Guidance",
    muted: "Muted",
    routeAlternatives: "Calculated Route Alternatives",
    pts: "pts",
    hazardRadar: "Hyderabad GIS Incident Radar",
    exposureIndex: "Exposure Index",
    pins: "Pins",
    adminLoginTitle: "Authority Sign In",
    adminLoginSub: "Restricted to GHMC officers. Accounts are created by an administrator.",
    emailLabel: "Email",
    passwordLabel: "Password",
    signIn: "Sign in",
    signingIn: "Signing in...",
    authInvalid: "Invalid email or password.",
    authNotConfigured: "Sign-in is unavailable because the backend (Supabase) is not configured.",
    authChecking: "Checking your session...",
    signedInAs: "Signed in as",
    backToCitizen: "Back to citizen app",
    enableAlerts: "Enable alerts",
    alertsOn: "Alerts on",
    alertsSoundBlocked: "Your browser blocked the alert sound. Click “Enable alerts”.",
    alertsHint: "Browsers block sound until you interact with the page.",
    newHighAlert: "New high-severity report",
    viewBtn: "View",
    dismissBtn: "Dismiss",
    unseenHighLabel: "Unseen high-severity reports",
    rtLive: "Live",
    rtPolling: "Polling (realtime unavailable)",
    rtConnecting: "Connecting",
    rtOffline: "Offline",
    typePothole: "Pothole",
    typeStreetlight: "Streetlight",
    typeGarbage: "Garbage / debris",
    typeWaterlogging: "Waterlogging",
    typeOther: "Other",
    statusReported: "Reported",
    statusDispatched: "Dispatched",
    statusInProgress: "In progress",
    statusResolved: "Resolved",
    statusRejected: "Rejected",
    assigneeLabel: "Assignee",
    assigneePlaceholder: "Crew or officer name",
    slaWillBe: "Resolution SLA for this severity",
    confirmDispatch: "Confirm dispatch",
    cancelBtn: "Cancel",
    startWork: "Start work",
    working: "Updating...",
    notDispatched: "Not dispatched yet",
    assignedTo: "Assigned to",
    slaDeadline: "SLA deadline",
    slaLeft: "left",
    slaOverdueBy: "Overdue by",
    exposureFormula: "Exposure = (severity × daily commuters) / 100",
    commuterEstimateNote: "Daily commuters estimated from Raastha route requests passing within ~30m in last 24h (+ road class baseline proxy).",
    exposureTieBreak: "Ties: higher severity first, then the older report.",
    estimateFromReports: "estimated from Raastha route requests",
    searchDestinationPlaceholder: "Search destination in Hyderabad (e.g. Charminar, Cyber Towers...)",
    searchingDestinations: "Searching places in Hyderabad...",
    noDestinationsFound: "No matching places found in Hyderabad.",
    quickDestinations: "Popular Landmarks",
    orsUnavailableNotice: "OpenRouteService routing unavailable",
    straightLineFallbackNotice: "Straight-line projected corridor is displayed as a fallback.",
    drivingProfile: "Driving",
    walkingProfile: "Walking",
    recommendedCorridor: "Recommended Safe Corridor",
    alternativeCorridor: "Alternative Corridor",
    actionFailed: "Action failed",
    resolveTitle: "Close ticket with repair proof",
    uploadAfterPhoto: "Upload the after-repair photo (required)",
    runAiCheck: "Run AI check (optional)",
    aiChecking: "Checking with AI...",
    aiUnavailable: "AI check unavailable. You can still close the ticket after reviewing the photo yourself.",
    aiFlaggedDefect: "AI flagged a possible remaining defect.",
    closeTicket: "Confirm & close ticket",
    closeAnyway: "Close anyway",
    allCategories: "All Hazard Types",
    confidenceLabel: "Confidence",
  },
  HI: {
    appName: "रास्ता",
    tagline: "आवाज-आधारित नागरिक सुरक्षा मंच",
    reportProblem: "समस्या की शिकायत करें",
    reportProblemSub: "सड़क के गड्ढों और अंधेरे स्थानों की तुरंत शिकायत दर्ज करें",
    safeRoute: "सुरक्षित मार्ग",
    safeRouteSub: "सड़क की समस्याओं से बचने वाला सुरक्षित मार्ग",
    myReports: "मेरी शिकायतें",
    myReportsSub: "अपनी दर्ज शिकायतों की वास्तविक स्थिति देखें",
    voicePromptPlaceholder: "माइक दबाएं या कहें 'गड्ढे की शिकायत दर्ज करें'",
    listening: "आवाज सुनी जा रही है...",
    speakNow: "अपनी भाषा में बोलें...",
    authorityPortal: "वार्ड कमान पोर्टल",
    sosButton: "आपातकालीन एसओएस",
    sosTriggered: "आपातकालीन स्थिति साझा करें",
    sosDesc: "व्हाट्सएप, एसएमएस या 112 कॉल द्वारा अपना स्थान तुरंत भेजें।",
    fastestRoute: "सीधा मार्ग",
    safestRoute: "सुरक्षित रोशन मार्ग",
    startNavigation: "सुरक्षित नेविगेशन शुरू करें",
    priorityScore: "प्राथमिकता अंक",
    exposureCount: "प्रभावित यात्री",
    slaTimer: "मरम्मत समय सीमा",
    verifyFix: "मरम्मत की जांच करें",
    reportSuccess: "शिकायत सफलतापूर्वक दर्ज की गई। ट्रैकिंग आईडी है",
    navStart: "सुरक्षित मार्ग नेविगेशन शुरू हो रहा है",
    navArrived: "आप सुरक्षित गलियारे से अपने गंतव्य पर पहुँच गए हैं!",
    sosActivated: "आपातकालीन अलर्ट सक्रिय। कृपया स्थान साझा करें या 112 डायल करें।",
    wardLabel: "सर्किल 8 - आबिड्स और नामपल्ली (केंद्रीय क्षेत्र), हैदराबाद",
    exposureRanked: "रैंकिंग एक्सपोज़र = (गंभीरता × दैनिक यात्री) / 100 पर आधारित",
    offlineNotice: "आप वर्तमान में ऑफ़लाइन हैं। नेटवर्क आते ही सिंक होगा।",
    dispatchSquad: "नगर पालिका दस्ता भेजें",
    assigningSquad: "दस्ता भेजा जा रहा है...",
    verifyResolve: "एआई द्वारा मरम्मत सत्यापित करें",
    fixNeutralized: "मरम्मत स्वीकृत और सुरक्षित",
    gpsDenied: "जीपीएस अनुमति उपलब्ध नहीं। केंद्र स्थान का उपयोग किया जा रहा है।",
    micDenied: "माइक्रोफोन अनुमति अस्वीकृत। कृपया नीचे लिखकर दर्ज करें।",
    voiceOpeningReport: "शिकायत फॉर्म खोला जा रहा है...",
    voiceOpeningRoute: "सुरक्षित रोशन मार्ग खोजा जा रहा है...",
    voiceOpeningMyReports: "आपकी दर्ज शिकायतें खोली जा रही हैं...",
    voiceOpeningSOS: "आपातकालीन सहायता पत्रक खोला जा रहा है...",
    voiceUnknownCommand: "आदेश समझ नहीं आया। 'शिकायत', 'सुरक्षित मार्ग', 'मेरी रिपोर्ट', या 'एसओएस' कहें।",
    sosAppsNotice: "ये बटन आपके फोन के ऐप्स खोलते हैं। रास्ता अपने आप अलर्ट नहीं भेजता है।",
    sampleDataBadge: "नमूना डेटा",
    liveReportBadge: "लाइव रिपोर्ट",
    adminPortalTitle: "एक्सपोजर-आधारित नगर निगम प्रेषण",
    adminPortalSubtitle: "स्वचालित प्राथमिकता कतार: प्राथमिकता = (गंभीरता × दैनिक यात्री) / 100",
    adminQueueTitle: "प्राथमिकता प्राप्त घटना प्रेषण कतार",
    statTotalIssues: "कुल सक्रिय समस्याएं",
    statSlaOverdue: "समय सीमा समाप्त",
    statUnitsDispatched: "सक्रिय दस्ते भेजे गए",
    statCommutersProtected: "सुरक्षित यात्री",
    filterAllCircles: "सभी हैदराबाद सर्किल",
    filterAllTypes: "सभी खतरे के प्रकार",
    signOut: "साइन आउट",
    navSelectDestination: "गंतव्य चुनें",
    navIlluminatedCorridor: "रोशन सुरक्षित मार्ग नेविगेशन",
    navSubtitle: "रोशन प्रमुख सड़कों को प्राथमिकता देने वाला जीपीएस नेविगेशन",
    turnByTurnNav: "कदम-दर-कदम नेविगेशन",
    nextDirection: "अगला कदम",
    destinationReached: "गंतव्य पर पहुंचे",
    voiceCommandBtn: "आवाज आदेश",
    wardSelectLabel: "नगर निगम सर्किल / वार्ड",
    wardAutoDetected: "निर्देशांक से स्वतः पहचाना गया (संपादनीय)",
    liveNavActive: "लाइव नेविगेशन सक्रिय",
    endTrip: "यात्रा समाप्त करें",
    voiceGuidance: "आवाज मार्गदर्शन",
    muted: "म्यूट",
    routeAlternatives: "गणना किए गए वैकल्पिक मार्ग",
    pts: "अंक",
    hazardRadar: "हैदराबाद जीआईएस घटना रडार",
    exposureIndex: "एक्सपोजर इंडेक्स",
    pins: "पिन",
    adminLoginTitle: "अधिकारी साइन इन",
    adminLoginSub: "केवल GHMC अधिकारियों के लिए। खाते प्रशासक द्वारा बनाए जाते हैं।",
    emailLabel: "ईमेल",
    passwordLabel: "पासवर्ड",
    signIn: "साइन इन",
    signingIn: "साइन इन हो रहा है...",
    authInvalid: "ईमेल या पासवर्ड गलत है।",
    authNotConfigured: "बैकएंड (Supabase) कॉन्फ़िगर नहीं है, इसलिए साइन इन उपलब्ध नहीं है।",
    authChecking: "आपका सत्र जांचा जा रहा है...",
    signedInAs: "साइन इन किया हुआ",
    backToCitizen: "नागरिक ऐप पर वापस जाएं",
    enableAlerts: "अलर्ट चालू करें",
    alertsOn: "अलर्ट चालू",
    alertsSoundBlocked: "ब्राउज़र ने अलर्ट ध्वनि रोक दी है। “अलर्ट चालू करें” दबाएं।",
    alertsHint: "पेज के साथ इंटरैक्ट करने तक ब्राउज़र ध्वनि रोकते हैं।",
    newHighAlert: "नई उच्च-गंभीरता की शिकायत",
    viewBtn: "देखें",
    dismissBtn: "हटाएं",
    unseenHighLabel: "अनदेखी उच्च-गंभीरता शिकायतें",
    rtLive: "लाइव",
    rtPolling: "पोलिंग (रीयलटाइम उपलब्ध नहीं)",
    rtConnecting: "कनेक्ट हो रहा है",
    rtOffline: "ऑफ़लाइन",
    typePothole: "गड्ढा",
    typeStreetlight: "स्ट्रीटलाइट",
    typeGarbage: "कचरा / मलबा",
    typeWaterlogging: "जलभराव",
    typeOther: "अन्य",
    statusReported: "दर्ज",
    statusDispatched: "भेजा गया",
    statusInProgress: "कार्य जारी",
    statusResolved: "हल हो गया",
    statusRejected: "अस्वीकृत",
    assigneeLabel: "नियुक्त व्यक्ति",
    assigneePlaceholder: "दल या अधिकारी का नाम",
    slaWillBe: "इस गंभीरता के लिए समाधान SLA",
    confirmDispatch: "प्रेषण की पुष्टि करें",
    cancelBtn: "रद्द करें",
    startWork: "कार्य शुरू करें",
    working: "अपडेट हो रहा है...",
    notDispatched: "अभी भेजा नहीं गया",
    assignedTo: "नियुक्त",
    slaDeadline: "SLA समय सीमा",
    slaLeft: "शेष",
    slaOverdueBy: "विलंब",
    exposureFormula: "एक्सपोज़र = (गंभीरता × दैनिक यात्री) / 100",
    commuterEstimateNote: "दैनिक यात्री पिछले 24 घंटों में 30 मीटर के भीतर गुजरने वाले रास्ता रूट अनुरोधों (+ सड़क वर्ग आधार) से अनुमानित हैं।",
    exposureTieBreak: "बराबरी पर: अधिक गंभीरता पहले, फिर पुरानी शिकायत।",
    estimateFromReports: "रास्ता मार्ग अनुरोधों से अनुमानित",
    searchDestinationPlaceholder: "हैदराबाद में गंतव्य खोजें (जैसे चारमीनार, साइबर टावर्स...)",
    searchingDestinations: "स्थान खोजे जा रहे हैं...",
    noDestinationsFound: "हैदराबाद में कोई मेल खाता स्थान नहीं मिला।",
    quickDestinations: "लोकप्रिय स्थल",
    orsUnavailableNotice: "ओपनरूटसर्विस रूटिंग अनुपलब्ध",
    straightLineFallbackNotice: "सीधे अनुमानित गलियारे को बैकअप के रूप में दिखाया गया है।",
    drivingProfile: "ड्राइविंग",
    walkingProfile: "पैदल",
    recommendedCorridor: "अनुशंसित सुरक्षित गलियारा",
    alternativeCorridor: "वैकल्पिक गलियारा",
    actionFailed: "कार्रवाई विफल रही",
    resolveTitle: "मरम्मत प्रमाण के साथ टिकट बंद करें",
    uploadAfterPhoto: "मरम्मत के बाद की फोटो अपलोड करें (आवश्यक)",
    runAiCheck: "एआई जांच चलाएं (वैकल्पिक)",
    aiChecking: "एआई से जांच हो रही है...",
    aiUnavailable: "एआई जांच उपलब्ध नहीं है। फोटो स्वयं देखकर आप टिकट बंद कर सकते हैं।",
    aiFlaggedDefect: "एआई ने संभावित शेष दोष बताया है।",
    closeTicket: "पुष्टि करें और टिकट बंद करें",
    closeAnyway: "फिर भी बंद करें",
    allCategories: "सभी खतरे के प्रकार",
    confidenceLabel: "विश्वास",
  },
  TE: {
    appName: "రాస్తా",
    tagline: "వాయిస్ ఆధారిత పౌర భద్రత వేదిక",
    reportProblem: "సమస్యను నివేదించండి",
    reportProblemSub: "రోడ్డు గుంతలు, విద్యుత్ దీపాల సమస్యలను తక్షణమే నివేదించండి",
    safeRoute: "సురక్షిత మార్గం",
    safeRouteSub: "చీకటి ప్రదేశాలను తప్పించే సురక్షిత వెలుతురు మార్గం",
    myReports: "నా నివేదికలు",
    myReportsSub: "మీరు నివేదించిన సమస్యల పరిష్కార పురోగతిని చూడండి",
    voicePromptPlaceholder: "మైక్ నొక్కండి లేదా 'గుంతను నివేదించండి' అని చెప్పండి",
    listening: "మీ మాట వినబడుతోంది...",
    speakNow: "మీ భాషలో మాట్లాడండి...",
    authorityPortal: "వార్డు కమాండ్ పోర్టల్",
    sosButton: "అత్యవసర SOS",
    sosTriggered: "అత్యవసర లొకేషన్ షేరింగ్",
    sosDesc: "వాట్సాప్, SMS లేదా 112 డైరెక్ట్ కాల్ ద్వారా మీ లొకేషన్ పంపండి.",
    fastestRoute: "నేరు మార్గం",
    safestRoute: "సురక్షిత వెలుతురు కారిడార్",
    startNavigation: "సురక్షిత నావిగేషన్ ప్రారంభించండి",
    priorityScore: "ప్రాధాన్యత స్కోరు",
    exposureCount: "ప్రయాణికుల సంఖ్య",
    slaTimer: "పరిష్కార గడువు",
    verifyFix: "పరిష్కారాన్ని ధృవీకరించండి",
    reportSuccess: "ఫిర్యాదు విజయవంతంగా నమోదు చేయబడింది. ట్రాకింగ్ ఐడి",
    navStart: "సురక్షిత మార్గ నావిగేషన్ ప్రారంభమవుతోంది",
    navArrived: "మీరు సురక్షితమైన వెలుతురు మార్గం ద్వారా మీ గమ్యస్థానానికి చేరుకున్నారు!",
    sosActivated: "అత్యవసర హెచ్చరిక ప్రారంభమైంది. దయచేసి లొకేషన్ షేర్ చేయండి లేదా 112కి కాల్ చేయండి.",
    wardLabel: "సర్కిల్ 8 - అబిడ్స్ మరియు నాంపల్లి (సెంట్రల్ జోన్), హైదరాబాద్",
    exposureRanked: "ర్యాంకింగ్ ఎక్స్‌పోజర్ = (తీవ్రత × రోజువారీ ప్రయాణికులు) / 100 ఆధారంగా",
    offlineNotice: "మీరు ప్రస్తుతం ఆఫ్‌లైన్‌లో ఉన్నారు. నెట్‌వర్క్ రాగానే సింక్ అవుతుంది.",
    dispatchSquad: "మున్సిపల్ బృందాన్ని పంపండి",
    assigningSquad: "బృందం కేటాయించబడుతోంది...",
    verifyResolve: "AI ద్వారా మరమ్మతును ధృవీకరించండి",
    fixNeutralized: "మరమ్మతు ఆమోదించబడింది",
    gpsDenied: "GPS అనుమతి లభించలేదు. కేంద్ర స్థానాన్ని ఉపయోగిస్తున్నాము.",
    micDenied: "మైక్రోఫోన్ అనుమతి నిరాకరించబడింది. దయచేసి క్రింద టైప్ చేయండి.",
    voiceOpeningReport: "ఫిర్యాదు ఫారమ్ తెరవబడుతోంది...",
    voiceOpeningRoute: "సురక్షిత వెలుతురు మార్గాన్ని కనుగొంటోంది...",
    voiceOpeningMyReports: "మీరు నివేదించిన సమస్యలు తెరవబడుతున్నాయి...",
    voiceOpeningSOS: "అత్యవసర సహాయ విండో తెరవబడుతోంది...",
    voiceUnknownCommand: "ఆదేశం గుర్తించబడలేదు. 'నివేదిక', 'సురక్షిత మార్గం', 'నా నివేదికలు', లేదా 'ఎస్ఓఎస్' అని చెప్పండి.",
    sosAppsNotice: "ఈ బటన్లు మీ స్వంత ఫోన్ యాప్‌లను తెరుస్తాయి. రాస్తా స్వతంత్రంగా హెచ్చరికలను పంపదు.",
    sampleDataBadge: "నమూనా డేటా",
    liveReportBadge: "ప్రత్యక్ష నివేదిక",
    adminPortalTitle: "ఎక్స్‌పోజర్-ఆధారిత మునిసిపల్ డిస్పాచ్",
    adminPortalSubtitle: "ఆటో-ర్యాంక్ క్యూ: ప్రాధాన్యత = (తీవ్రత × రోజువారీ ప్రయాణికులు) / 100",
    adminQueueTitle: "ప్రాధాన్యతా ప్రమాదాల డిస్పాచ్ క్యూ",
    statTotalIssues: "మొత్తం క్రియాశీల సమస్యలు",
    statSlaOverdue: "గడువు ముగిసినవి",
    statUnitsDispatched: "రంగంలోకి దిగిన బృందాలు",
    statCommutersProtected: "రక్షించబడిన ప్రయాణికులు",
    filterAllCircles: "అన్ని హైదరాబాద్ సర్కిళ్లు",
    filterAllTypes: "అన్ని ప్రమాద రకాలు",
    signOut: "లాగ్ అవుట్",
    navSelectDestination: "గమ్యస్థానాన్ని ఎంచుకోండి",
    navIlluminatedCorridor: "వెలుతురు సురక్షిత కారిడార్ నావిగేషన్",
    navSubtitle: "వెలుతురున్న ప్రధాన రహదారులను ప్రాధాన్యమిచ్చే GPS నావిగేషన్",
    turnByTurnNav: "మలుపుల వారీ నావిగేషన్",
    nextDirection: "తదుపరి దశ",
    destinationReached: "గమ్యస్థానానికి చేరుకున్నారు",
    voiceCommandBtn: "వాయిస్ కమాండ్",
    wardSelectLabel: "మునిసిపల్ సర్కిల్ / వార్డు",
    wardAutoDetected: "కోఆర్డినేట్ల నుండి గుర్తించబడింది (సవరించవచ్చు)",
    liveNavActive: "ప్రత్యక్ష నావిగేషన్ ప్రారంభమైంది",
    endTrip: "ట్రిప్ ముగించు",
    voiceGuidance: "వాయిస్ గైడెన్స్",
    muted: "మ్యూట్",
    routeAlternatives: "లెక్కించిన ప్రత్యామ్నాయ మార్గాలు",
    pts: "పాయింట్లు",
    hazardRadar: "హైదరాబాద్ GIS ఇన్సిడెంట్ రాడార్",
    exposureIndex: "ఎక్స్‌పోజర్ సూచిక",
    pins: "పిన్స్",
    adminLoginTitle: "అధికారి సైన్ ఇన్",
    adminLoginSub: "GHMC అధికారులకు మాత్రమే. ఖాతాలను అడ్మినిస్ట్రేటర్ సృష్టిస్తారు.",
    emailLabel: "ఈమెయిల్",
    passwordLabel: "పాస్‌వర్డ్",
    signIn: "సైన్ ఇన్",
    signingIn: "సైన్ ఇన్ అవుతోంది...",
    authInvalid: "ఈమెయిల్ లేదా పాస్‌వర్డ్ తప్పు.",
    authNotConfigured: "బ్యాకెండ్ (Supabase) కాన్ఫిగర్ చేయలేదు, కాబట్టి సైన్ ఇన్ అందుబాటులో లేదు.",
    authChecking: "మీ సెషన్ తనిఖీ చేస్తోంది...",
    signedInAs: "సైన్ ఇన్ అయినవారు",
    backToCitizen: "పౌర యాప్‌కు తిరిగి వెళ్ళండి",
    enableAlerts: "అలర్ట్‌లు ఆన్ చేయండి",
    alertsOn: "అలర్ట్‌లు ఆన్",
    alertsSoundBlocked: "బ్రౌజర్ అలర్ట్ శబ్దాన్ని నిరోధించింది. “అలర్ట్‌లు ఆన్ చేయండి” నొక్కండి.",
    alertsHint: "మీరు పేజీతో ఇంటరాక్ట్ అయ్యే వరకు బ్రౌజర్లు శబ్దాన్ని నిరోధిస్తాయి.",
    newHighAlert: "కొత్త అధిక-తీవ్రత నివేదిక",
    viewBtn: "చూడండి",
    dismissBtn: "మూసివేయి",
    unseenHighLabel: "చూడని అధిక-తీవ్రత నివేదికలు",
    rtLive: "లైవ్",
    rtPolling: "పోలింగ్ (రియల్‌టైమ్ అందుబాటులో లేదు)",
    rtConnecting: "కనెక్ట్ అవుతోంది",
    rtOffline: "ఆఫ్‌లైన్",
    typePothole: "గుంత",
    typeStreetlight: "వీధి దీపం",
    typeGarbage: "చెత్త / శిథిలాలు",
    typeWaterlogging: "నీటి నిల్వ",
    typeOther: "ఇతర",
    statusReported: "నివేదించబడింది",
    statusDispatched: "పంపబడింది",
    statusInProgress: "పనులు జరుగుతున్నాయి",
    statusResolved: "పరిష్కరించబడింది",
    statusRejected: "తిరస్కరించబడింది",
    assigneeLabel: "కేటాయించబడినవారు",
    assigneePlaceholder: "బృందం లేదా అధికారి పేరు",
    slaWillBe: "ఈ తీవ్రతకు పరిష్కార SLA",
    confirmDispatch: "పంపడాన్ని నిర్ధారించండి",
    cancelBtn: "రద్దు",
    startWork: "పని ప్రారంభించండి",
    working: "నవీకరిస్తోంది...",
    notDispatched: "ఇంకా పంపలేదు",
    assignedTo: "కేటాయించబడింది",
    slaDeadline: "SLA గడువు",
    slaLeft: "మిగిలింది",
    slaOverdueBy: "ఆలస్యం",
    exposureFormula: "ఎక్స్‌పోజర్ = (తీవ్రత × రోజువారీ ప్రయాణికులు) / 100",
    commuterEstimateNote: "గత 24 గంటల్లో 30 మీటర్ల పరిధిలో వెళ్లిన రాస్తా రూట్ అభ్యర్థనల నుండి లెక్కించబడిన ప్రయాణికులు (+ రోడ్డు తరగతి ప్రాక్సీ).",
    exposureTieBreak: "సమానమైతే: ఎక్కువ తీవ్రత ముందు, తర్వాత పాత నివేదిక.",
    estimateFromReports: "రాస్తా రూట్ అభ్యర్థనల నుండి అంచనా వేయబడింది",
    searchDestinationPlaceholder: "హైదరాబాద్‌లో గమ్యస్థానాన్ని శోధించండి (ఉదా. చార్మినార్, సైబర్ టవర్స్...)",
    searchingDestinations: "స్థలాలు శోధించబడుతున్నాయి...",
    noDestinationsFound: "హైదరాబాద్‌లో సరిపోలే స్థలాలు కనుగొనబడలేదు.",
    quickDestinations: "ప్రసిద్ధ ప్రదేశాలు",
    orsUnavailableNotice: "ఓపెన్‌రూట్‌సర్వీస్ రూటింగ్ అందుబాటులో లేదు",
    straightLineFallbackNotice: "నేరు కారిడార్ ఫాల్‌బ్యాక్‌గా చూపించబడుతోంది.",
    drivingProfile: "డ్రైవింగ్",
    walkingProfile: "నడక",
    recommendedCorridor: "సిఫార్సు చేయబడిన సురక్షిత కారిడార్",
    alternativeCorridor: "ప్రత్యామ్నాయ కారిడార్",
    actionFailed: "చర్య విఫలమైంది",
    resolveTitle: "మరమ్మతు రుజువుతో టికెట్ మూసివేయండి",
    uploadAfterPhoto: "మరమ్మతు తర్వాత ఫోటో అప్‌లోడ్ చేయండి (తప్పనిసరి)",
    runAiCheck: "AI తనిఖీ చేయండి (ఐచ్ఛికం)",
    aiChecking: "AI తో తనిఖీ చేస్తోంది...",
    aiUnavailable: "AI తనిఖీ అందుబాటులో లేదు. ఫోటోను మీరే చూసి టికెట్‌ను మూసివేయవచ్చు.",
    aiFlaggedDefect: "ఇంకా లోపం ఉండవచ్చని AI సూచించింది.",
    closeTicket: "నిర్ధారించి టికెట్ మూసివేయండి",
    closeAnyway: "అయినా మూసివేయండి",
    allCategories: "అన్ని ప్రమాద రకాలు",
    confidenceLabel: "నమ్మకం",
  },
};
